name: Linux
on: [ push, pull_request ]

env:
  REPO: template-cpp
  GITHUB_REPO: Kubaaa96/template-cpp

jobs:
  windows:
    name: Linux ( Ubuntu )
    runs-on: ubuntu-22.04
    env:
      CMAKE_INSTALL_PREFIX: "${{ github.workspace }}\\install"
    strategy:
      matrix:
        CONFIG:
          - {
            BUILD_TYPE: Release,
            CC: gcc-11.2,
            CXX: g++-11.2
          }
          - {
            BUILD_TYPE: Debug,
            CC: gcc-11.2,
            CXX: g++-11.2
          }
          - {
            BUILD_TYPE: Release,
            CC: clang-14,
            CXX: clang++-14
          }
          - {
            BUILD_TYPE: Debug,
            CC: clang-14,
            CXX: clang++-14
          }
    steps:
      - name: Print environment variables
        run: env

      - name: Print compiler version
        env:
          CC: ${{ matrix.CONFIG.CC }}
          CXX: ${{ matrix.CONFIG.CXX }}
        run: |
          "$CC" --version
          "$CXX" --version