name: Linux
on: [ push, pull_request ]

env:
  REPO: template-cpp
  GITHUB_REPO: Kubaaa96/template-cpp

jobs:
  windows:
    name: Linux ( Ubuntu )
    runs-on: ubuntu-latest
    env:
      GENERATOR: "Visual Studio 17 2022"
      ARCH: "x64"
      CMAKE_INSTALL_PREFIX: "${{ github.workspace }}\\install"
    strategy:
      matrix:
        CONFIG:
          - {
            BUILD_TYPE: Release,
            CC: gcc-10,
            CXX: g++-10
          }
          - {
            BUILD_TYPE: Debug,
            CC: gcc-10,
            CXX: g++-10
          }
          - {
            BUILD_TYPE: Release,
            CC: clang-9,
            CXX: clang++-9
          }
          - {
            BUILD_TYPE: Debug,
            CC: clang-9,
            CXX: clang++-9
          }
    steps:
      - name: Print environment variables
        run: env

      - name: Print compiler version
        env:
          CC: ${{ matrix.CONFIG.CC }}
          CXX: ${{ matrix.CONFIG.CXX }}
        run: |
          "$CC" --version
          "$CXX" --version