name: MacOS
on: [ push, pull_request ]

env:
  REPO: template-cpp
  GITHUB_REPO: Kubaaa96/template-cpp

jobs:
  linux:
    name: MacOS 12
    runs-on: macos-12
    strategy:
      matrix:
        CONFIG:
          - {
            BUILD_TYPE: Debug,
            CC: gcc-11,
            CXX: g++-11
          }
          - {
            BUILD_TYPE: Debug,
            CC: $(brew --prefix llvm@14)/bin/clang,
            CXX: $(brew --prefix llvm@14)/bin/clang++
          }
    steps:
      - name: Install Conan
        run: pip3 install conan

      - name: Clone the git repo
        uses: actions/checkout@v2
        with:
          path: project
          fetch-depth: 50

      - name: Create project build directory
        working-directory: project
        run: |
          mkdir build
          cd build

      - name: Configure project
        working-directory: project
        run: cmake -Bbuild
          -DCMAKE_BUILD_TYPE="${{ matrix.CONFIG.BUILD_TYPE }}"
          -DCMAKE_C_COMPILER="${{ matrix.CONFIG.CC }}"
          -DCMAKE_CXX_COMPILER="${{ matrix.CONFIG.CXX }}" .

      - name: Build project
        working-directory: project
        run: cmake --build ./build --config ${{ matrix.CONFIG.BUILD_TYPE }}  -- -j $(nproc --all)

      - name: Run tests
        working-directory: project/build/tests
        run: ctest -C ${{ matrix.CONFIG.BUILD_TYPE }} --output-on-failure --timeout 540

      - name: Basic Coverage
        working-directory: project
        run: gcovr -r . --exclude-throw-branches --exclude-unreachable-branches