name: Windows
on: [ push, pull_request ]

env:
  REPO: template-cpp
  GITHUB_REPO: Kubaaa96/template-cpp

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      GENERATOR: "Visual Studio 17 2022"
      ARCH: "x64"
      CMAKE_INSTALL_PREFIX: "${{ github.workspace }}\\install"
    strategy:
      matrix:
        CONFIG:
          - {
            BUILD_TYPE: Release
          }
          - {
            BUILD_TYPE: Debug
          }
    steps:
      - name: Install Conan
        run: pip install conan

      - name: Clone the git repo
        uses: actions/checkout@v2
        with:
          path: project
          fetch-depth: 50

      - name: Create project build directory
        working-directory: project
        run: |
          mkdir build
          cd build

      - name: Configure project
        working-directory: project
        run: cmake -Bbuild
          -DCMAKE_BUILD_TYPE="${{ matrix.CONFIG.BUILD_TYPE }}"
          -DCMAKE_C_COMPILER="${{ matrix.CONFIG.CC }}"
          -DCMAKE_CXX_COMPILER="${{ matrix.CONFIG.CXX }}" .

      - name: Build project
        working-directory: project
        run: cmake --build ./build --config ${{ matrix.CONFIG.BUILD_TYPE }}  -- -j $(nproc --all)

      - name: Run tests
        working-directory: project/build/tests
        run: ctest -C ${{ matrix.CONFIG.BUILD_TYPE }} --output-on-failure --timeout 540